export const metadata = {
  title: 'About Page',
  description: 'Generated by create next app',
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div> About Layout</div>
      {children}
    </>
  );
}
